### ISSUE TITLE
是否有一个uni项目作为另一个uni项目的分包的解决方案?

### ISSUE THREAD

**Issue by yangbean4** [devilwjp/uniapp2wxpack#10]
目前的场景是,公司已有的小程序(主小程序)是使用uni开发的.  后续要开展一系列的活动希望同时部署为H5和主小程序中的页面.
请问uniapp2wxpack是否能够解决这种场景? 有没有可行的方案?  谢谢🙏

**Comment by yangbean4** [comment]
目前在尝试的是先将分包使用build为subpackage 并认为该subpackage为原生小程序开发的页面.  随后使用uniapp2wxpack将subpackage在主uni项目中使用.  请问这种方案是否可行呢? 有无其它更好的方案?

**Comment by devilwjp** [comment]
首先，你的方案是可行的，然后你的方案稍作优化就会变的优雅，我的理解是你现在的方案在subpackage项目无法进行调试模式（因为你是build出来的），所以你觉得不够优雅，你可以同时通过`npm run dev:mp-weixin-pack`运行你的子项目和主项目（都通过uniapp2wxpack），将子项目的dist/dev/mp-weixin-pack/subpackage目录通过symlink（软链接的方式，windows下可能需要管理员权限）关联到你主项目的src/wxresource/subpackage中，然后在你主项目的pages.json中配置wxResource的分包，这样就可以进行两个项目融合的开发调试热更新了  
```
// pages.json
{
	"pages": [
		{
			"path": "pages/about/about",
			"style": {
				"navigationBarTitleText": "主uni页面"
			}
		}
	]
	"wxResource":{
		"subPackages":[{
			"root": "subpackage",
			"pages": ["index"]
		}]
	}
}
```
