### ISSUE TITLE
小程序分包 relegation 模式bug

### ISSUE THREAD

**Issue by thisdj** [devilwjp/uniapp2wxpack#16]
appMode
relegation (降级模式，默认)
降级模式的含义是将uni目录从项目级别降级到了目录级别，那么App.vue中的钩子函数就只对目录有效
比如：App.vue中的onLaunch，会降级成首次进入uni目录才触发，同样的，onHide会降级成只要离开uni目录的范围就会触发

这个模式下，onLaunch的参数会丢失。

**Comment by devilwjp** [comment]
好的，我跟进一下这个情况 @thisdj

**Comment by devilwjp** [comment]
我验证了一下，并没有发现问题，app.vue的onLaunch的参数是可以拿到的，可以跑下一示例项目https://github.com/devilwjp/uni-project-to-subpackage  
项目安装之后，运行npm run dev:mp-weixin-pack  
![image](https://user-images.githubusercontent.com/38802722/150918569-4502e114-8fdc-4fa6-bd36-0387722307cb.png)  
![image](https://user-images.githubusercontent.com/38802722/150918632-bed92e3f-6960-4ee5-8e32-f62bd08f5a2c.png)  
![image](https://user-images.githubusercontent.com/38802722/150918868-c40b9325-7950-409b-8879-b53d7e998b9a.png)


@thisdj

**Comment by thisdj** [comment]
是分包里的onLaunch取不到哦，主包的onLaunch是没问题。

**Comment by devilwjp** [comment]
@thisdj 
测试了从微信原生小程序首页直接跳转到一个uni的分包页面，依旧会触发uni的app.vue的onLaunch，并且参数依旧会带的，并且又测了把整个uni作为分包，从首页跳到任何一个uni页面，仍然可以触发以及传递参数  
我已更新了示范项目，点击首页的“Hello World”文字就会跳到/uniSubpackage/pages/test/about，这是一个uni项目的分包  
![image](https://user-images.githubusercontent.com/38802722/151170437-9361f279-0927-4c5d-be12-5b7565e3c78b.png)
![image](https://user-images.githubusercontent.com/38802722/151170533-d6d90717-89ae-4288-a96a-eca2ff7083d6.png)

**Comment by thisdj** [comment]
![a](https://user-images.githubusercontent.com/24769836/153104398-2466f10e-10a5-44b7-9795-344e9f3a40f9.png)
@devilwjp 新年好，示例中的跳转并未传参，我加了参数后，如图。

**Comment by devilwjp** [comment]
@thisdj 明白了，我排查一下，新年好！

**Comment by devilwjp** [comment]
@thisdj 我理解你的问题了，relegation模式的onLaunch返回的依旧应该是小程序真正首页的的参数，你可以看到path依旧是pages/index/index，而非uni目录的首页地址

**Comment by devilwjp** [comment]
@thisdj 你可以尝试一下把首页进入地址改成uni目录的某个页面，onLaunch就是你希望看到的样子了，onLaunch必须返回真实的小程序onLaunch信息，否则uni目录的页面就无法获取到小程序真实进入情况了  
![image](https://user-images.githubusercontent.com/38802722/153109446-7d25a822-1845-4969-949c-b44b368df15e.png)

**Comment by devilwjp** [comment]
@thisdj relegation模式的uni目录第一次被访问到的页面才会触发app.vue的onLaunch，并且获取到的是真正的小程序的onLaunch信息，此时可以结合getCurrentPage方法获取当前页面的参数和路径进行相关复杂逻辑的判断和处理

**Comment by thisdj** [comment]
好的，明白了，谢谢。
