### ISSUE TITLE
vendor.js压缩问题

### ISSUE THREAD

**Issue by lilibin0519** [devilwjp/uniapp2wxpack#4]
请问，生成微信小程序后，vendor.js将近900kb，这个可以通过哪些配置调整吗？我暂时没找到，麻烦告知一下，谢谢

**Comment by devilwjp** [comment]
@lilibin0519 如果你是build模式, vendor.js已经被进行过压缩, 如果要进一步压缩, 就要使用分包(并且启动uniapp的分包优化功能)  
如果你还是dev模式,  那么导出的js是不经过压缩的, 如果想进行压缩可以在package.json的命令后面增加 --minimize的参数(见uniapp官方说明),但是这个压缩模式只是局限的,因为是dev模式,压缩过的js中还是会带有sourcemap  
我的回答希望对你有帮助

**Comment by devilwjp** [comment]
@lilibin0519 从你900Kb的描述情况分析,你应该就是普通的dev模式, 900K包含vue和uni的基础组件以及webpack的相关函数, 进入build模式后会缩小到300K左右, 300K也是uniapp项目最小的极限
