### ISSUE TITLE
如何发布支付宝小程序插件？

### ISSUE THREAD

**Issue by feixiang001** [devilwjp/uniapp2wxpack#7]
如何发布支付宝小程序插件？

**Comment by devilwjp** [comment]
@feixiang001 暂时还不支持支付宝小程序插件，现在只支持微信小程序插件  
需求已收集，一周左右可支持，开发模式会类似微信小程序插件，可以先了解下微信小程序插件的开发

**Comment by devilwjp** [comment]
@feixiang001 其实使用uni开发小程序插件还是有一些问题，就是只能开放js接口和插件页面，组件的话在原生小程序使用还是会有问题，只能显示，不能传属性特别是事件，除非是使用在uni的小程序中，这方面正在想办法解决

**Comment by devilwjp** [comment]
@feixiang001 uniapp2wxpack@alipay-plugin
